new Vue({
    el:"#root",
    data:{
        datas:[
            {
                id:1,
                title:11
            },
            {
                id:2,
                title:22
            },
            {
                id:3,
                title:33
            }
        ],
        state:false,
        title:""
    },
    methods:{
        aa(){
            this.state=true;
        },
        bb(val){
            this.title=val;
            this.state=false
        },
    }
});